# Generated by Django 2.2.6 on 2019-11-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191104_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(verbose_name='生日'),
        ),
    ]
