# Generated by Django 2.2.6 on 2019-11-04 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catename', models.CharField(max_length=32)),
                ('remark', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ingname', models.CharField(max_length=32)),
                ('Ingquantity', models.FloatField()),
                ('Ingdescript', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNum', models.CharField(max_length=16)),
                ('serialDption', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Taste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tastename', models.CharField(max_length=32)),
                ('remark', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('rcp_id', models.AutoField(primary_key=True, serialize=False)),
                ('rcp_name', models.CharField(max_length=64)),
                ('rcp_descript', models.CharField(max_length=255)),
                ('rcp_imgurl', models.CharField(default='#', max_length=255)),
                ('cateid', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='recipe.Category')),
                ('tasteid', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='recipe.Taste')),
                ('userid', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='user.User')),
            ],
        ),
    ]
