# Generated by Django 2.2.6 on 2019-11-27 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20191127_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='rcpId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipe'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='rcpId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipe'),
        ),
    ]
