# Generated by Django 2.2.6 on 2019-11-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_avatar'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
    ]
