# Generated by Django 2.2.6 on 2019-11-29 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20191127_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['comment_time']},
        ),
    ]
