# Generated by Django 2.2.6 on 2019-11-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='likes_num',
        ),
        migrations.AddField(
            model_name='collections',
            name='is_collect',
            field=models.BooleanField(default=False),
        ),
    ]
