# Generated by Django 2.2.6 on 2019-11-17 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0006_stores_total_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='活动名称')),
                ('abstract', models.TextField(verbose_name='活动详情')),
                ('host_time', models.DateTimeField()),
                ('host_address', models.CharField(max_length=20)),
                ('participants', models.PositiveIntegerField(default=0)),
                ('contactPhone', models.CharField(max_length=11)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('total_view', models.PositiveIntegerField(default=0)),
                ('remark', models.TextField(verbose_name='备注')),
                ('chargeMan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Stores')),
            ],
        ),
    ]
