# Generated by Django 2.2.6 on 2019-11-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20191117_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodactivity',
            name='host_address',
            field=models.CharField(max_length=128),
        ),
    ]
