# Generated by Django 2.2.6 on 2019-11-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20191117_1718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodActivity',
        ),
    ]
