# Generated by Django 2.2.6 on 2019-11-18 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_avatar'),
        ('activity', '0005_foodactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truename', models.CharField(max_length=32)),
                ('mobile', models.CharField(max_length=11)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.FoodActivity')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
