# Generated by Django 2.2.6 on 2019-11-05 13:47

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_auto_20191105_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtcCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atcCate_name', models.CharField(max_length=32)),
                ('atcCate_remark', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('abstract', models.CharField(max_length=200, null=True, verbose_name='摘要')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_time', models.DateTimeField()),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('is_top', models.CharField(default=0, max_length=1)),
                ('atc_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.AtcCategory')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_author', to='user.User')),
            ],
        ),
    ]
