# Generated by Django 2.2.6 on 2019-11-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='店铺名称')),
                ('tabstract', models.CharField(blank=True, max_length=255, null=True, verbose_name='店铺概要')),
                ('introdution', models.TextField(verbose_name='简介')),
                ('discount', models.CharField(blank=True, max_length=200, null=True, verbose_name='优惠信息')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('ontime', models.CharField(max_length=128, verbose_name='营业时间')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
            ],
        ),
    ]
