# Generated by Django 2.2.6 on 2019-11-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='img',
            field=models.ImageField(default='#', upload_to='upload_path'),
        ),
    ]
