# Generated by Django 2.2.6 on 2019-11-06 11:44

import apps.store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_stores_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='img',
            field=models.ImageField(upload_to=apps.store.models.Stores.upload_path),
        ),
    ]
