# Generated by Django 2.2.6 on 2019-11-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20191106_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stores',
            old_name='introdution',
            new_name='introduction',
        ),
    ]
