# Generated by Django 2.2.6 on 2019-11-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20191106_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='店铺名称'),
        ),
    ]
