# Generated by Django 2.2.6 on 2019-11-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20191106_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='total_view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
